import type { ParameterDefinition } from "../types/parameters";

export const rendererParameterSchema: ParameterDefinition[] = [
  {
    key: "paddingX",
    label: "Horizontal Padding",
    type: "number",
    defaultValue: 24,
    min: 0,
    max: 220,
    step: 1,
    tab: "Renderer",
    category: "Size / Position",
  },
  {
    key: "paddingY",
    label: "Vertical Padding",
    type: "number",
    defaultValue: 22,
    min: 0,
    max: 220,
    step: 1,
    tab: "Renderer",
    category: "Size / Position",
  },
  {
    key: "centerYOffset",
    label: "Center Y Offset",
    type: "number",
    defaultValue: 0,
    min: -0.45,
    max: 0.45,
    step: 0.01,
    tab: "Renderer",
    category: "Size / Position",
  },
  {
    key: "baseRadiusRatio",
    label: "Base Radius Ratio",
    type: "number",
    defaultValue: 0.22,
    min: 0.05,
    max: 0.48,
    step: 0.01,
    tab: "Renderer",
    category: "Size / Position",
    visibleWhen: [{ key: "layout", equals: "circle" }],
  },
  {
    key: "backgroundColor",
    label: "Background",
    type: "color",
    defaultValue: "#050816",
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "trailAlpha",
    label: "Trail Alpha",
    type: "number",
    defaultValue: 0.35,
    min: 0,
    max: 1,
    step: 0.01,
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "colorMode",
    label: "Color Mode",
    type: "select",
    defaultValue: "gradient",
    options: [
      { label: "Gradient", value: "gradient" },
      { label: "Solid", value: "solid" },
    ],
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "primaryColor",
    label: "Primary Color",
    type: "color",
    defaultValue: "#66f0ff",
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "secondaryColor",
    label: "Secondary Color",
    type: "color",
    defaultValue: "#6e4dff",
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "colorMode", equals: "gradient" }],
  },
  {
    key: "opacity",
    label: "Opacity",
    type: "number",
    defaultValue: 1,
    min: 0.05,
    max: 1,
    step: 0.01,
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "outlineEnabled",
    label: "Outline Enabled",
    type: "boolean",
    defaultValue: false,
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "outlineColor",
    label: "Outline Color",
    type: "color",
    defaultValue: "#f4f7ff",
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "outlineEnabled", equals: true }],
  },
  {
    key: "outlineWidth",
    label: "Outline Width",
    type: "number",
    defaultValue: 1.5,
    min: 0.5,
    max: 16,
    step: 0.1,
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "outlineEnabled", equals: true }],
  },
  {
    key: "glowEnabled",
    label: "Glow Enabled",
    type: "boolean",
    defaultValue: true,
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "glowColor",
    label: "Glow Color",
    type: "color",
    defaultValue: "#9ce7ff",
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "glowEnabled", equals: true }],
  },
  {
    key: "glowBlur",
    label: "Glow Blur",
    type: "number",
    defaultValue: 20,
    min: 0,
    max: 120,
    step: 1,
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "glowEnabled", equals: true }],
  },
  {
    key: "shadowEnabled",
    label: "Shadow Enabled",
    type: "boolean",
    defaultValue: false,
    tab: "Renderer",
    category: "Style",
  },
  {
    key: "shadowColor",
    label: "Shadow Color",
    type: "color",
    defaultValue: "#111827",
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "shadowEnabled", equals: true }],
  },
  {
    key: "shadowBlur",
    label: "Shadow Blur",
    type: "number",
    defaultValue: 8,
    min: 0,
    max: 80,
    step: 1,
    tab: "Renderer",
    category: "Style",
    visibleWhen: [{ key: "shadowEnabled", equals: true }],
  },
  {
    key: "vizType",
    label: "Visualizer Type",
    type: "select",
    defaultValue: "bar",
    options: [
      { label: "Bar", value: "bar" },
      { label: "Line", value: "line" },
      { label: "Dot", value: "dot" },
      { label: "Solid", value: "solid" },
    ],
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "layout",
    label: "Layout",
    type: "select",
    defaultValue: "straight",
    options: [
      { label: "Straight", value: "straight" },
      { label: "Circle", value: "circle" },
    ],
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "lowCutoffPercent",
    label: "Low Cutoff %",
    type: "number",
    defaultValue: 0,
    min: 0,
    max: 0.95,
    step: 0.01,
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "highCutoffPercent",
    label: "High Cutoff %",
    type: "number",
    defaultValue: 1,
    min: 0.05,
    max: 1,
    step: 0.01,
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "intensity",
    label: "Intensity",
    type: "number",
    defaultValue: 1.1,
    min: 0.1,
    max: 4,
    step: 0.05,
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "responseCurve",
    label: "Response Curve",
    type: "number",
    defaultValue: 0.9,
    min: 0.2,
    max: 2,
    step: 0.05,
    tab: "Renderer",
    category: "Type",
  },
  {
    key: "mirror",
    label: "Mirror",
    type: "boolean",
    defaultValue: true,
    tab: "Renderer",
    category: "Type",
    visibleWhen: [{ key: "layout", equals: "straight" }],
  },
  {
    key: "radialSpin",
    label: "Radial Spin",
    type: "number",
    defaultValue: 0,
    min: 0,
    max: 2,
    step: 0.01,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "layout", equals: "circle" }],
  },
  {
    key: "barWidthScale",
    label: "Bar Width Scale",
    type: "number",
    defaultValue: 1,
    min: 0.25,
    max: 2.5,
    step: 0.05,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "vizType", equals: "bar" }],
  },
  {
    key: "barGap",
    label: "Bar Gap",
    type: "number",
    defaultValue: 2,
    min: 0,
    max: 24,
    step: 0.5,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [
      { key: "vizType", equals: "bar" },
      { key: "layout", equals: "straight" },
    ],
  },
  {
    key: "minBarHeight",
    label: "Min Bar Height",
    type: "number",
    defaultValue: 2,
    min: 0,
    max: 64,
    step: 1,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "vizType", equals: "bar" }],
  },
  {
    key: "lineWidth",
    label: "Line Width",
    type: "number",
    defaultValue: 2,
    min: 0.5,
    max: 16,
    step: 0.1,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "vizType", equals: ["line", "solid"] }],
  },
  {
    key: "dotSize",
    label: "Dot Size",
    type: "number",
    defaultValue: 3,
    min: 1,
    max: 20,
    step: 0.5,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "vizType", equals: "dot" }],
  },
  {
    key: "solidFillAlpha",
    label: "Solid Fill Alpha",
    type: "number",
    defaultValue: 0.35,
    min: 0.05,
    max: 1,
    step: 0.01,
    tab: "Renderer",
    category: "Type-Specific",
    visibleWhen: [{ key: "vizType", equals: "solid" }],
  },
];
